[package]
name = "glitchbomb"
version = "0.0.0"
cairo-version = "2.13.1"
edition = "2024_07"

[scripts]

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
collection.workspace = true
starterpack.workspace = true
graffiti.workspace = true
openzeppelin.workspace = true
alexandria_encoding.workspace = true
dojo.workspace = true
dojo_cairo_macros.workspace = true
starknet.workspace = true

[dev-dependencies]
dojo_cairo_test.workspace = true
cairo_test.workspace = true

[features]
default = []

[profile.slot]
[profile.mainnet]
[profile.sepolia]
